### ISSUE TITLE
Notch dimensions

### ISSUE THREAD

**Issue by hacker1024** [ResurrectionRemix-Devices/device_xiaomi_beryllium#1]
[The notch dimensions can be specified as detailed here.](https://source.android.com/devices/tech/display/display-cutouts)
[It's already been implemented in the LineageOS device tree here.](https://github.com/LineageOS/android_device_xiaomi_beryllium/blob/4697e326ba3a1270da471bdc9779876ee51995eb/overlay/frameworks/base/core/res/res/values/config.xml#L198-L217)

**Comment by hacker1024** [comment]
Oh, I was looking at the `oreo` branch. It's been implemented.

**Comment by EnesSastim** [comment]
oof ;_;
